### ISSUE TITLE
Day 10

### ISSUE THREAD

**Issue by jasolerolmos** [VectorSVK/AdventOfCode2020#1]
First, thanks for your Code.
I toke your Day2Part2 and the solutions is not the same. With my Input, the solution is 3947645370368 but with your code i got 3947645370368.

I didn't those Part, but i found other Code and i could get the good solution.

This is my Input.

18
47
144
147
124
45
81
56
16
59
97
83
75
150
33
165
30
159
84
141
104
25
164
90
92
88
2
8
51
24
153
63
27
123
127
58
108
52
38
15
149
66
72
21
46
89
135
55
34
37
78
65
134
148
76
138
103
162
114
109
42
77
102
163
7
105
69
39
91
111
131
130
6
137
96
82
64
3
95
136
85
9
116
17
99
12
117
62
50
110
26
115
71
57
156
120
98
1
70

**Comment by 0xVector** [comment]
I've tried your input with three different codes and got three different solutions to part 2. You posted the same number twice, as I understand it, **3947645370368** is the answer that you got accepted for part 2 (please correct me if I'm wrong). 

Anyway, thanks for letting me know, I'll look into the code to see what's the problem with my solution.

**Comment by jasolerolmos** [comment]
Sorry!!! I copied wrong solution.
With your code i take 986911342592 but the answer is 3947645370368.

```
What is the total number of distinct ways you can arrange the adapters to connect the charging outlet to your device?

Your puzzle answer was 3947645370368.
```

I don't remember where i took this code:

```
from collections import OrderedDict as odict, Counter

jolts = sorted(int(x) for x in open("input10.txt").read().strip().split("\n"))
jolts = [0] + jolts + [jolts[-1] + 3]

# Part 1.
counter = Counter(jolts[i+1] - jolt for i, jolt in enumerate(jolts[:-1]))
print("Part 1:", (counter[1] * counter[3]))

# Part 2.
dag = odict([(x, {y for y in range(x+1, x+4) if y in jolts}) for x in jolts])


def dfc(D, v, M={}):
    "Memoized depth first counter"
    if v in M:
        return M[v]
    elif D[v]:
        M[v] = sum(dfc(D, x, M) for x in D[v])
        return M[v]
    else:
        return 1

print("Part 2:", dfc(dag, 0))
```
Thanks for your time.

**Comment by 0xVector** [comment]
Fixed in commit https://github.com/0xVector/AdventOfCode2020/commit/6919d95c7918e55efb50bd429dc4f6d9372a8e82.
Just a tiny mistake in my code. I also rewrote the code to be much simpler in commit https://github.com/0xVector/AdventOfCode2020/commit/cabc2ee0a3322594c6756b52a70741d4636325b4. 

Thanks for reporting!
